window.PORTFOLIO_DATA = {
  githubUsername: 'jahidbappi',
  name: 'Jahid',
  fullName: 'Md. Jahidul Islam',
  title: 'AI Engineer · Full Stack Developer · Database Specialist',
  tagline: 'Problem first. Code second.',
  bio: 'Obsessed learner. I just love coding.',
  philosophy: 'First, solve the problem. Then, write the code.',
  description:
    'Full-stack engineer specializing in web applications, database architecture, and AI/ML—from live products to production-ready client work.',
  profileImage: 'assets/profile.jpg',
  profileImageAlt: 'Md. Jahidul Islam — Full Stack Developer',
  social: {
    github: 'https://github.com/jahidbappi',
    linkedin: 'https://linkedin.com/in/jahidbappi',
    email: 'jahidcric2000@gmail.com',
    medium: 'https://medium.com/@jahidcric2000',
    twitter: 'https://twitter.com/jahidbappi_',
    location: 'Bangladesh',
    portfolio: 'https://jahidbappi.vercel.app',
  },
  web3formsAccessKey: 'YOUR_WEB3FORMS_ACCESS_KEY',

  heroRoles: [
    'systems that scale.',
    'full-stack products.',
    'AI-powered tools.',
    'database solutions.',
  ],

  heroStats: [
    { value: '13+', label: 'Repositories' },
    { value: '29+', label: 'Play Store apps' },
    { value: '4+', label: 'Certifications' },
  ],

  aboutHighlights: [
    'Production deployments',
    'Database architecture',
    'AI integrations',
    'Client web apps',
  ],

  skillGroups: [
    {
      title: 'Languages',
      icon: 'fa-code',
      accent: 'violet',
      skills: ['Python', 'JavaScript', 'TypeScript', 'C++', 'C#', 'Java', 'Swift', 'PHP'],
    },
    {
      title: 'Databases & ORMs',
      icon: 'fa-database',
      accent: 'violet',
      skills: ['Oracle', 'MySQL', 'PostgreSQL', 'MongoDB', 'Entity Framework'],
    },
    {
      title: 'Full-Stack Web',
      icon: 'fa-layer-group',
      accent: 'violet',
      featured: true,
      skills: ['React', 'Node.js', 'Django', 'Flask', 'REST APIs', 'HTML & CSS'],
    },
    {
      title: 'AI & Machine Learning',
      icon: 'fa-brain',
      accent: 'violet',
      skills: ['TensorFlow', 'PyTorch', 'scikit-learn', 'Pandas', 'NumPy'],
    },
    {
      title: 'DevOps & Cloud',
      icon: 'fa-cloud',
      accent: 'violet',
      skills: ['AWS', 'Azure', 'Docker', 'Kubernetes', 'Vercel'],
    },
    {
      title: 'Tools & IDEs',
      icon: 'fa-wrench',
      accent: 'violet',
      skills: ['Git', 'VS Code', 'Cursor', 'Jupyter', 'Postman', 'Android Studio'],
    },
  ],

  focusingOn: ['PyTorch', 'AWS Certification', 'Microservices'],

  certifications: [
    { title: 'Python for Everybody', provider: 'Coursera', year: '2024' },
    { title: 'Oracle Database Expert', provider: 'Oracle Academy', year: '2023' },
    { title: 'AWS Certified Developer', provider: 'Amazon Web Services', year: '2024' },
    { title: 'TensorFlow Developer', provider: 'Google', year: '2024' },
  ],

  experience: [
    {
      period: '2025 — Present',
      title: 'Full-Stack Developer',
      subtitle: 'VibeFlow',
      description: 'Shipped a software-selling platform — React, Node.js, live on Vercel.',
      tags: ['React', 'Node.js', 'Vercel'],
    },
    {
      period: '2024 — Present',
      title: 'Web Developer',
      subtitle: 'Client Projects',
      description: 'Responsive business websites — performance-first and accessible.',
      tags: ['HTML/CSS', 'JavaScript', 'UI/UX'],
    },
    {
      period: '2025',
      title: 'AI Tools Builder',
      subtitle: 'code-reviewer-ai',
      description: 'AI code review tool with instant multi-language feedback.',
      tags: ['TypeScript', 'AI', 'DevTools'],
    },
    {
      period: '2025',
      title: 'University Lead',
      subtitle: 'Web Technologies',
      description: 'Final-term full-stack PHP group project with modern frontend practices.',
      tags: ['PHP', 'MySQL', 'Team Lead'],
    },
  ],

  excludedRepos: ['jahidbappi', 'Web-Technologies_Course-Tasks'],

  repoCategoryOverrides: {
    'code-reviewer-ai': 'ai',
    'Understanding-PRISMA': 'ai',
    'BFS-path-search': 'ai',
    'numpy_power_tools': 'ai',
    TicTacToe: 'mobile',
    'Identifier-Length-Limit-Tester': 'web',
    VibeFlow: 'web',
    Smart_Relief_BD: 'web',
    'Web-Technologies-Project_Group-08': 'web',
    'A-Digital-Tapestry-of-City-and-Nature': 'web',
    'Password-checker': 'web',
  },

  featuredLiveProjects: [
    {
      name: 'VibeFlow',
      description: 'Modern software selling platform with React frontend and full-stack capabilities.',
      category: 'web',
      tech: ['React', 'Node.js', 'JavaScript'],
      github: 'https://github.com/jahidbappi/VibeFlow',
      live: 'https://vibe-flow.vercel.app',
      featured: true,
    },
    {
      name: 'code-reviewer-ai',
      description: 'AI-powered instant code review tool across multiple languages.',
      category: 'ai',
      tech: ['TypeScript', 'AI', 'React'],
      github: 'https://github.com/jahidbappi/code-reviewer-ai',
      live: null,
      featured: true,
    },
    {
      name: 'Identifier-Length-Limit-Tester',
      description: 'React tool for testing identifier length limits across compilers and databases.',
      category: 'web',
      tech: ['React', 'JavaScript'],
      github: 'https://github.com/jahidbappi/Identifier-Length-Limit-Tester',
      live: null,
      featured: true,
    },
    {
      name: 'Web-Technologies-Project_Group-08',
      description: 'Final-term full-stack web project built with PHP and modern practices.',
      category: 'web',
      tech: ['PHP', 'MySQL', 'JavaScript'],
      github: 'https://github.com/jahidbappi/Web-Technologies-Project_Group-08',
      live: null,
      featured: false,
    },
    {
      name: 'Smart_Relief_BD',
      description: 'Full-stack disaster relief and resource management platform.',
      category: 'web',
      tech: ['Full-Stack', 'Web App'],
      github: 'https://github.com/jahidbappi/Smart_Relief_BD',
      live: null,
      featured: false,
    },
  ],

  mobileGroups: [
    {
      id: 'business',
      label: 'Business & Service Apps',
      icon: 'fa-briefcase',
      projects: [
        { name: 'Ditto Frame', description: 'Professional video recording booking service for weddings, birthday.', play: 'https://play.google.com/store/apps/details?id=com.dittorecordingslimited.dittoframe' },
        { name: 'Solvify -H H Solutions', description: 'Office admin services. Order, track, PDFs. No permissions, no data collection.', play: 'https://play.google.com/store/apps/details?id=com.hhsolutionsltd.solvofy' },
        { name: 'Ditto Coffee LTD', description: 'Premium coffee ordering with instant PDF receipts. Private, offline, and simple.', play: 'https://play.google.com/store/apps/details?id=com.dittocoffeemanchesterlimited.dittocoffee' },
        { name: 'Kouakio LTD', description: 'Your complete health and safety product catalog and service ordering app.', play: 'https://play.google.com/store/apps/details?id=com.kouakioltd.kouakiohealth' },
        { name: 'Farorote Consultancy', description: 'IT consulting services app — browse services, book consultations.', play: 'https://play.google.com/store/apps/details?id=com.faroroteltd.faroroteconsultancy' },
        { name: 'PRIMEPICK Traders Delivery', description: 'Professional delivery requests with instant PDF summaries. Safe and reliable.', play: 'https://play.google.com/store/apps/details?id=com.primepicktradersltd.primepickdelivery' },
        { name: 'Primepick Traders', description: 'Curated tech and lifestyle essentials with concierge service.', play: 'https://play.google.com/store/apps/details?id=com.primepicktradersltd.primepicktraders' },
        { name: 'CBN Barbers', description: 'Premium mobile barber services. Book haircuts and grooming at your door.', play: 'https://play.google.com/store/apps/details?id=com.cbnmobilebarberltd.cbnbarbers' },
        { name: 'ERWG Homes', description: 'Explore projects, order services, and connect with real estate development.', play: 'https://play.google.com/store/apps/details?id=com.erwgoedhomesltd.erwghomes' },
        { name: 'Clarion Flow', description: 'Professional bookkeeping and payroll services for UK businesses.', play: 'https://play.google.com/store/apps/details?id=com.clarionpayrollserviceslimited.clarionflow' },
        { name: 'Noyan Wholesale', description: 'Wholesale textiles by NOYAN LIMITED. Browse products.', play: 'https://play.google.com/store/apps/details?id=com.noyanlimited.noyanwholesale' },
        { name: 'DORL Cars', description: 'Browse vehicles, book test drives, and order services from Dickens of Wrexham.', play: 'https://play.google.com/store/apps/details?id=com.dickensofwrexhamlimited.dorlcars' },
        { name: 'CDM Music', description: 'Browse music and video catalog, order services, and get PDF confirmations.', play: 'https://play.google.com/store/apps/details?id=com.cdmmusiclimited.cdmmusic' },
        { name: 'SNL Wheelz', description: 'Curated used vehicles and simple service orders in a privacy-first app.', play: 'https://play.google.com/store/apps/details?id=com.solonwlimited.snlwheelz' },
        { name: 'Crafts and More', description: 'Handmade food, craft drinks, and more. Browse the menu, no account required.', play: 'https://play.google.com/store/apps/details?id=com.handmadeandmoreltd.craftandmore' },
        { name: 'Bottin Consult', description: 'Boutique legal app: services, orders, on-device PDFs, and firm insights.', play: 'https://play.google.com/store/apps/details?id=com.bottincreekconsultingltd.bottinconsult' },
        { name: 'Aurelio Decor', description: 'Wholesale furniture, carpets & lighting — browse, order drafts & PDFs on-device.', play: 'https://play.google.com/store/apps/details?id=com.goldenblindsltd.aureliodecor' },
        { name: 'Baseonix', description: 'Browse Baseonix catalog, build requests, export PDFs on your device.', play: 'https://play.google.com/store/apps/details?id=com.archibaseltd.baseonix' },
      ],
    },
    {
      id: 'games',
      label: 'Games',
      icon: 'fa-gamepad',
      projects: [
        { name: '3Patti Octro:Fortune Card', description: 'Buy intel and master card-stacking in our mini-game. Perfect your timing now!', play: 'https://play.google.com/store/apps/details?id=net.octrogame.patticard' },
        { name: 'Jhandi Munda King', description: 'Jhandi Munda King is back — the classic dice game you know and love!', play: 'https://play.google.com/store/apps/details?id=net.mdipbnt.jhandimunda.king' },
        { name: 'Teen Patti Bodhi-Lucky Ace', description: 'Download Teen Patti Bodhi now and start your lucky journey!', play: 'https://play.google.com/store/apps/details?id=net.luckybodhi.lucky.ace' },
        { name: 'Whimsy Balloon Link Puzzle', description: 'Link matching balloons to clear the board.', play: 'https://play.google.com/store/apps/details?id=com.whimsy.balloon.link.puzzle' },
        { name: 'Critter Burst Tile Bash', description: 'Chain matching tiles for powerful bomb blasts.', play: 'https://play.google.com/store/apps/details?id=com.critter.burst.tile.bash' },
        { name: 'Puzzle Adventure', description: 'Embark on a wonderful adventure with jigsaw puzzles.', play: 'https://play.google.com/store/apps/details?id=com.yx.puzzle.adv' },
        { name: 'Link Level Up', description: 'Keep linking and level up!', play: 'https://play.google.com/store/apps/details?id=com.yx.link.level.up' },
        { name: 'Twist Bolt', description: 'Just twist the bolts!', play: 'https://play.google.com/store/apps/details?id=com.yx.twist.bolt' },
        { name: 'Bubble Fruit Zap', description: 'Embark on a fruit matching quest.', play: 'https://play.google.com/store/apps/details?id=com.yx.bubble.fruit.zap' },
      ],
    },
    {
      id: 'utility',
      label: 'Utilities & Tools',
      icon: 'fa-wrench',
      projects: [
        { name: 'Antivirus Spark', description: 'Virus scanning, junk cleaning, and photo & video management.', play: 'https://play.google.com/store/apps/details?id=com.avsparklabs.mobile.sec' },
        { name: 'Hypno Clock', description: 'Relax with a swinging pocket watch and ambient breathing sessions.', play: 'https://play.google.com/store/apps/details?id=com.app.hypnoclock' },
      ],
    },
  ],
};
